spaces = ' '*25
print('%s 12 Butts wynd' % spaces)
print('%s Twinklebottom Heath' % spaces)
print('%s West Snoring' % spaces)
print()
print()
print('Dear Sir')
print()
print('I wish to report thattiles are missing from the')
print('outside toilet roof.')
print('I think it was bad wind the other night that blew them awy.')
print()
print('Regards')
print('Malcolm Dithering')

